//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicateurAirAtlantique
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirAtlantiqueEntities : DbContext
    {
        public AirAtlantiqueEntities()
            : base("name=AirAtlantiqueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Avion> Avion { get; set; }
        public DbSet<Capacite> Capacite { get; set; }
        public DbSet<TypePlace> TypePlace { get; set; }
        public DbSet<VentesPlaces> VentesPlaces { get; set; }
        public DbSet<Ville> Ville { get; set; }
        public DbSet<Vol> Vol { get; set; }
        public DbSet<CapaciteLigne> CapaciteLigne { get; set; }
        public DbSet<CapaciteVol> CapaciteVol { get; set; }
        public DbSet<Frequentation> Frequentation { get; set; }
        public DbSet<VentesPlacesLigne> VentesPlacesLigne { get; set; }
        public DbSet<VentesPlacesVol> VentesPlacesVol { get; set; }
    }
}
