//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicateurAirAtlantique
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapaciteLigne
    {
        public string villeDepart { get; set; }
        public string villeArrive { get; set; }
        public Nullable<int> capaciteLigne1 { get; set; }
    }
}
