//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicateurAirAtlantique
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentesPlaces
    {
        public int idVol { get; set; }
        public int idTypePlace { get; set; }
        public int nbPlace { get; set; }
        public double prix { get; set; }
    
        public virtual TypePlace TypePlace { get; set; }
        public virtual Vol Vol { get; set; }
    }
}
