//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicateurAirAtlantique
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ville
    {
        public Ville()
        {
            this.Vol = new HashSet<Vol>();
            this.Vol1 = new HashSet<Vol>();
        }
    
        public string nom { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
    
        public virtual ICollection<Vol> Vol { get; set; }
        public virtual ICollection<Vol> Vol1 { get; set; }
    }
}
