//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicateurAirAtlantique
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vol
    {
        public Vol()
        {
            this.VentesPlaces = new HashSet<VentesPlaces>();
        }
    
        public int id { get; set; }
        public System.DateTime dateVol { get; set; }
        public string villeDepart { get; set; }
        public string villeArrive { get; set; }
        public int idAvion { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual ICollection<VentesPlaces> VentesPlaces { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual Ville Ville1 { get; set; }
    }
}
